# Snowflake Short-term-rentals Profile
# -------------------
# Move this file to desired location and
# set DBT_PROFILES_DIR in .env. For more info:
# https://docs.getdbt.com/dbt-cli/configure-your-profile
# -------------------

   short_term_rental_profile:
     outputs:
       dev:
         type: snowflake
         threads: 4
         account: "{{ env_var('SNOW_ACCOUNT') }}"

         user: "{{ env_var('SNOW_USER') }}"
         password: "{{ env_var('SNOW_PASS') }}"
         role: transformer

         database: ANALYTICS
         warehouse: TRANSFORMING
         schema: MODEL
     target: dev
