version: 2

models:
  - name: stg_costs
    description: This model cleans up cost of living data.
    columns:
      - name: cost_rank
        description: The ranking that the source gives each city from most expensive to least.
        tests:
          - unique
          - not_null
      - name: living_idx
        tests:
          - not_null
      - name: rent_idx
        tests:
          - not_null
      - name: costs_city_name
        tests:
          - not_null
      - name: city_country_name
        tests:
          - unique
  - name: stg_population
    description: This model cleans up city population data.
    columns:
      - name: pop_city_name
        tests:
          - not_null
      - name: population
        tests:
          - not_null
      - name: country_code
        tests:
          - not_null
  - name: stg_listings
    description: This model cleans up Airbnb listing data.
    columns:
      - name: listing_city
        tests:
          - not_null
      - name: room_type
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']