version: 2

models:
  - name: stg_costs
    columns:
      - name: rank
        tests:
          - unique
          - not_null
      - name: living_idx
        tests:
          - not_null
      - name: rent_idx
        tests:
          - not_null
      - name: costs_city
        tests:
          - not_null
      - name: city_country
        tests:
          - unique
  - name: stg_population
    columns:
      - name: pop_city
        tests:
          - not_null
      - name: population
        tests:
          - not_null
      - name: country_code
        tests:
          - not_null
  - name: stg_listings
    columns:
      - name: listing_city
        tests:
          - not_null
      - name: room_type
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']